#!/bin/bash

cordova build android --release
cp platforms/android/build/outputs/apk/android-armv7-release-unsigned.apk android-armv7-release.apk
jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore my-release-key.keystore android-armv7-release.apk alias_name
# password: yiteng
