#!/bin/bash

gulp bump --patch
cordova build android --release
cp platforms/android/build/outputs/apk/android-armv7-release-unsigned.apk ./
jarsigner \
  -verbose \
  -sigalg SHA1withRSA \
  -digestalg SHA1 \
  -keystore signatures/android.keystore \
  android-armv7-release-unsigned.apk \
  alias_name

# password: yiteng
